import argparse
import json
import logging
import math
import os
import random
from pathlib import Path

import numpy as np
import torch
try:
    import torch_npu
except ImportError:
    pass
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import transforms
from tqdm.auto import tqdm
from datasets import load_dataset, load_from_disk

from accelerate import Accelerator
from accelerate.utils import set_seed
from transformers import CLIPTextModel, CLIPTokenizer, CLIPModel
from pretrained_encoder.protein_clip_adapter import ProteinCLIPAdapter, get_device, empty_cache

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


DATASET_NAME_MAPPING = {
    "magic2life/birds_9": ("image", "text"),
}


def is_npu_available():
    return hasattr(torch, 'npu') and torch.npu.is_available()


def parse_args():
    parser = argparse.ArgumentParser(description="Align protein encoder to CLIP text encoder space")
    parser.add_argument("--pretrained_model_name_or_path", type=str, required=True)
    parser.add_argument("--species_encoder_config", type=str, default=None)
    parser.add_argument("--dataset_name", type=str, default=None,
                        help="HuggingFace dataset name or local path for protein-image parquet")
    parser.add_argument("--dataset_config_name", type=str, default=None)
    parser.add_argument("--train_data_dir", type=str, default=None)
    parser.add_argument("--image_column", type=str, default="image")
    parser.add_argument("--caption_column", type=str, default="text")
    parser.add_argument("--description_dataset", type=str, default=None,
                        help="Path to description parquet dataset (image + description columns). "
                             "Generated by csv_to_parquet.py. If provided, description text is used "
                             "for feature regression loss instead of 'a photo of {species}'.")
    parser.add_argument("--description_column", type=str, default="description",
                        help="Column name for description text in description dataset")
    parser.add_argument("--output_dir", type=str, default="alignment_output")
    parser.add_argument("--num_train_epochs", type=int, default=50)
    parser.add_argument("--max_train_steps", type=int, default=None)
    parser.add_argument("--train_batch_size", type=int, default=8,
                        help="Per-GPU batch size")
    parser.add_argument("--learning_rate", type=float, default=1e-4)
    parser.add_argument("--lr_warmup_steps", type=int, default=500)
    parser.add_argument("--weight_decay", type=float, default=0.01)
    parser.add_argument("--adam_beta1", type=float, default=0.9)
    parser.add_argument("--adam_beta2", type=float, default=0.999)
    parser.add_argument("--adam_epsilon", type=float, default=1e-8)
    parser.add_argument("--max_grad_norm", type=float, default=1.0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--checkpointing_steps", type=int, default=500)
    parser.add_argument("--resume_from_checkpoint", type=str, default=None)
    parser.add_argument("--mixed_precision", type=str, default=None, choices=["no", "fp16", "bf16"])
    parser.add_argument("--loss_feature_weight", type=float, default=1.0,
                        help="Weight for feature regression loss (protein -> CLIP text from description)")
    parser.add_argument("--loss_contrastive_weight", type=float, default=0.5,
                        help="Weight for contrastive loss (protein <-> image via CLIP vision)")
    parser.add_argument("--loss_classify_weight", type=float, default=0.1,
                        help="Weight for species classification loss")
    parser.add_argument("--use_clip_vision", action="store_true",
                        help="Enable contrastive loss with CLIP vision encoder")
    parser.add_argument("--clip_model_path", type=str, default=None,
                        help="Path to local full CLIP model (e.g. openai/clip-vit-large-patch14). "
                             "Required for --use_clip_vision if SD directory does not contain full CLIP model.")
    parser.add_argument("--species_encoder_checkpoint", type=str, default=None,
                        help="Path to a previously trained adapter checkpoint to resume from")
    parser.add_argument("--num_workers", type=int, default=8)
    parser.add_argument("--prefetch_factor", type=int, default=4)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=1)
    parser.add_argument("--resolution", type=int, default=512)
    parser.add_argument("--validation_split", type=float, default=0.1)
    parser.add_argument("--cache_dir", type=str, default=None)
    return parser.parse_args()


def extract_species_from_protein_text(protein_text):
    parts = protein_text.split(',')
    for part in parts:
        part = part.strip()
        if part.startswith('tr|') or part.startswith('sp|'):
            segments = part.split('|')
            if len(segments) >= 3:
                species_tag = segments[2]
                species_parts = species_tag.split('_')
                if len(species_parts) >= 2:
                    return f"{species_parts[0]}_{species_parts[1]}"
    return None


def build_description_lookup(description_dataset_path, description_column="description"):
    logger.info(f"Loading description dataset from {description_dataset_path}...")
    try:
        desc_ds = load_from_disk(description_dataset_path)
    except Exception:
        desc_ds = load_dataset(description_dataset_path, split="train")

    if isinstance(desc_ds, dict):
        if "train" in desc_ds:
            desc_ds = desc_ds["train"]
        else:
            first_key = list(desc_ds.keys())[0]
            desc_ds = desc_ds[first_key]

    lookup = {}
    desc_list = desc_ds[description_column]
    image_col = desc_ds["image"] if "image" in desc_ds.column_names else None

    for i in range(len(desc_ds)):
        desc = desc_list[i]
        if not desc:
            continue
        key = str(i)
        if image_col is not None:
            img = image_col[i]
            if hasattr(img, 'filename') and img.filename:
                key = os.path.basename(img.filename)
            elif hasattr(img, 'path') and img.path:
                key = os.path.basename(img.path)
        lookup[key] = desc

    logger.info(f"Description lookup built: {len(lookup)} entries")
    return lookup


def main():
    args = parse_args()

    accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        mixed_precision=args.mixed_precision,
        log_with=None,
    )

    if is_npu_available():
        logger.info(f"Detected {torch.npu.device_count()} NPU device(s)")
    else:
        try:
            import torch_npu
            logger.warning("torch_npu installed but no NPU devices detected")
        except ImportError:
            logger.warning(
                "torch_npu is NOT installed! NPU training requires torch_npu. "
                "Install with: pip install torch_npu"
            )

    if args.seed is not None:
        set_seed(args.seed)

    os.makedirs(args.output_dir, exist_ok=True)

    weight_dtype = torch.float32
    if args.mixed_precision == "fp16":
        weight_dtype = torch.float16
    elif args.mixed_precision == "bf16":
        weight_dtype = torch.bfloat16

    script_dir = Path(__file__).resolve().parent
    encoder_config_path = Path(args.species_encoder_config) if args.species_encoder_config else script_dir / "pretrained_encoder" / "config.yml"
    import yaml
    with open(encoder_config_path, 'rb') as f:
        config = yaml.safe_load(f)

    config_base_dir = encoder_config_path.parent
    embeddings_path = str(config_base_dir / config['embeddings']) if not Path(config['embeddings']).is_absolute() else config['embeddings']
    species_classes_path = str(config_base_dir / config['species_classes']) if not Path(config['species_classes']).is_absolute() else config['species_classes']
    vocabulary_path = str(config_base_dir / config['vocabulary']) if not Path(config['vocabulary']).is_absolute() else config['vocabulary']

    with open(species_classes_path, 'r') as f:
        species_id = json.load(f)
    species_name_to_id = species_id

    description_lookup = None
    if args.description_dataset is not None:
        description_lookup = build_description_lookup(args.description_dataset, args.description_column)

    logger.info("Initializing ProteinCLIPAdapter...")
    model = ProteinCLIPAdapter(
        pretrained_model_name_or_path=args.pretrained_model_name_or_path,
        embeddings_dir=embeddings_path,
        vocabulary_path=vocabulary_path,
        species_classes_path=species_classes_path,
        max_tokens=config['max_tokens'],
        device="cpu",
    )

    if args.species_encoder_checkpoint is not None:
        logger.info(f"Loading adapter checkpoint: {args.species_encoder_checkpoint}")
        ckpt = torch.load(args.species_encoder_checkpoint, map_location="cpu")
        model.load_state_dict(ckpt, strict=False)

    model.clip_text_model.requires_grad_(False)
    model.protein_embedding_layer.requires_grad_(False)
    model.clip_text_model.eval()
    model.protein_embedding_layer.eval()

    trainable_params = []
    for name, param in model.named_parameters():
        if param.requires_grad:
            trainable_params.append(param)
            logger.info(f"  Trainable: {name}, shape={tuple(param.shape)}")

    total_trainable = sum(p.numel() for p in trainable_params)
    logger.info(f"Total trainable parameters: {total_trainable:,}")

    clip_text_encoder = None
    text_encoder_dir = os.path.join(args.pretrained_model_name_or_path, "text_encoder")
    parent_text_encoder_dir = os.path.join(os.path.dirname(args.pretrained_model_name_or_path), "text_encoder")
    for path in [text_encoder_dir, parent_text_encoder_dir, args.pretrained_model_name_or_path]:
        if os.path.isdir(path) and any(
            os.path.isfile(os.path.join(path, f))
            for f in ["config.json", "model.safetensors", "pytorch_model.bin"]
        ):
            try:
                clip_text_encoder = CLIPTextModel.from_pretrained(path)
                break
            except Exception:
                continue
    if clip_text_encoder is None:
        raise RuntimeError("无法从本地加载 CLIP text encoder，请确认目录中包含 config.json 和模型权重文件")
    clip_text_encoder.requires_grad_(False)
    clip_text_encoder.eval()

    clip_tokenizer = None
    tokenizer_dir = os.path.join(args.pretrained_model_name_or_path, "tokenizer")
    parent_dir = os.path.dirname(args.pretrained_model_name_or_path)
    parent_tokenizer_dir = os.path.join(parent_dir, "tokenizer") if os.path.basename(args.pretrained_model_name_or_path) == "text_encoder" else None
    for path in [tokenizer_dir, parent_tokenizer_dir, args.pretrained_model_name_or_path, parent_dir]:
        if path is None or not os.path.isdir(path):
            continue
        if os.path.isfile(os.path.join(path, "tokenizer_config.json")):
            try:
                clip_tokenizer = CLIPTokenizer.from_pretrained(path)
                break
            except Exception:
                continue
    if clip_tokenizer is None:
        raise RuntimeError("无法从本地加载 CLIP tokenizer，请确认目录中包含 tokenizer_config.json")

    clip_vision_model = None
    clip_visual_projection = None
    clip_text_projection = None
    if args.use_clip_vision:
        logger.info("Loading CLIP vision model for contrastive loss...")
        full_clip = None
        if args.clip_model_path is not None:
            try:
                full_clip = CLIPModel.from_pretrained(args.clip_model_path)
            except Exception as e:
                raise RuntimeError(f"无法从 --clip_model_path 加载 CLIP 模型: {e}")
        if full_clip is None:
            sd_root = os.path.dirname(args.pretrained_model_name_or_path) if os.path.basename(args.pretrained_model_name_or_path) == "text_encoder" else args.pretrained_model_name_or_path
            for path in [sd_root, args.pretrained_model_name_or_path]:
                if os.path.isdir(path) and os.path.isfile(os.path.join(path, "config.json")):
                    try:
                        with open(os.path.join(path, "config.json"), 'r') as f:
                            _cfg = json.load(f)
                        if _cfg.get("model_type") != "clip":
                            continue
                        full_clip = CLIPModel.from_pretrained(path)
                        break
                    except Exception:
                        continue
        if full_clip is None:
            logger.info("SD 目录不包含完整 CLIP 模型，尝试从 HuggingFace 加载 openai/clip-vit-large-patch14...")
            try:
                full_clip = CLIPModel.from_pretrained("openai/clip-vit-large-patch14")
            except Exception as e:
                raise RuntimeError(
                    f"无法加载 CLIP vision model。SD 目录中不包含完整 CLIP 模型（只有 text_encoder），"
                    f"且无法从 HuggingFace 下载。请手动下载 openai/clip-vit-large-patch14 后"
                    f"使用 --clip_model_path 指定本地路径。原始错误: {e}"
                )
        clip_vision_model = full_clip.vision_model
        clip_visual_projection = full_clip.visual_projection
        clip_text_projection = full_clip.text_projection
        clip_vision_model.requires_grad_(False)
        clip_visual_projection.requires_grad_(False)
        clip_text_projection.requires_grad_(False)
        clip_vision_model.eval()

    num_species = len(species_name_to_id)
    classify_head = nn.Linear(model.clip_hidden_dim, num_species)

    logger.info("Loading protein-image dataset...")
    if args.dataset_name is not None:
        dataset = load_dataset(
            args.dataset_name,
            args.dataset_config_name,
            cache_dir=args.cache_dir,
            data_dir=args.train_data_dir,
        )
    else:
        data_files = {}
        if args.train_data_dir is not None:
            data_files["train"] = os.path.join(args.train_data_dir, "**")
        dataset = load_dataset(
            "imagefolder",
            data_files=data_files,
            cache_dir=args.cache_dir,
        )

    if "train" not in dataset:
        raise ValueError("Dataset must have a 'train' split")

    full_dataset = dataset["train"]
    split = full_dataset.train_test_split(test_size=args.validation_split, seed=args.seed)
    train_dataset = split["train"]
    val_dataset = split["test"]
    logger.info(f"Train samples: {len(train_dataset)}, Val samples: {len(val_dataset)}")

    column_names = train_dataset.column_names
    image_column = args.image_column if args.image_column in column_names else column_names[0]
    caption_column = args.caption_column if args.caption_column in column_names else column_names[1]
    logger.info(f"Using image_column='{image_column}', caption_column='{caption_column}'")

    clip_vision_resolution = 224
    image_transform = transforms.Compose([
        transforms.Resize(clip_vision_resolution, interpolation=transforms.InterpolationMode.BILINEAR),
        transforms.CenterCrop(clip_vision_resolution),
        transforms.ToTensor(),
        transforms.Normalize([0.48145466, 0.4578275, 0.40821073],
                             [0.26862954, 0.26130258, 0.27577711]),
    ])

    def get_image_basename(img):
        if hasattr(img, 'filename') and img.filename:
            return os.path.basename(img.filename)
        if hasattr(img, 'path') and img.path:
            return os.path.basename(img.path)
        return None

    def preprocess_train(examples):
        images = []
        image_basenames = []
        for img in examples[image_column]:
            if img is not None:
                images.append(image_transform(img.convert("RGB")))
                bn = get_image_basename(img)
                image_basenames.append(bn if bn else "")
            else:
                images.append(torch.zeros(3, clip_vision_resolution, clip_vision_resolution))
                image_basenames.append("")

        protein_seqs = []
        for caption in examples[caption_column]:
            if isinstance(caption, str):
                protein_seqs.append(caption)
            elif isinstance(caption, (list, np.ndarray)):
                protein_seqs.append(caption[0])
            else:
                protein_seqs.append(str(caption))

        descriptions = []
        if description_lookup is not None:
            for bn in image_basenames:
                desc = description_lookup.get(bn, "")
                if not desc:
                    sp = extract_species_from_protein_text(protein_seqs[len(descriptions)] if len(descriptions) < len(protein_seqs) else "")
                    desc = f"a photo of {sp.replace('_', ' ')}" if sp else "a photo of a bird"
                descriptions.append(desc)

        examples["pixel_values"] = images
        examples["protein_seq"] = protein_seqs
        examples["description"] = descriptions
        return examples

    def preprocess_val(examples):
        protein_seqs = []
        image_basenames = []
        for i, caption in enumerate(examples[caption_column]):
            if isinstance(caption, str):
                protein_seqs.append(caption)
            elif isinstance(caption, (list, np.ndarray)):
                protein_seqs.append(caption[0])
            else:
                protein_seqs.append(str(caption))

        for img in examples[image_column]:
            bn = get_image_basename(img)
            image_basenames.append(bn if bn else "")

        descriptions = []
        if description_lookup is not None:
            for i, bn in enumerate(image_basenames):
                desc = description_lookup.get(bn, "")
                if not desc:
                    sp = extract_species_from_protein_text(protein_seqs[i]) if i < len(protein_seqs) else ""
                    desc = f"a photo of {sp.replace('_', ' ')}" if sp else "a photo of a bird"
                descriptions.append(desc)

        examples["protein_seq"] = protein_seqs
        examples["description"] = descriptions
        return examples

    with open(species_classes_path, 'r') as f:
        species_id_map = json.load(f)

    train_dataset = train_dataset.with_transform(preprocess_train)
    val_dataset = val_dataset.with_transform(preprocess_val)

    protein_tokenizer = model.tokenizer

    def collate_fn_train(examples):
        pixel_values = torch.stack([e["pixel_values"] for e in examples])
        protein_seqs = [e["protein_seq"] for e in examples]
        descriptions = [e.get("description", "") for e in examples]

        protein_tokens = protein_tokenizer(
            protein_seqs,
            max_length=protein_tokenizer.model_max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )

        clip_text_inputs = []
        for i, desc in enumerate(descriptions):
            if desc:
                clip_text_inputs.append(desc)
            else:
                sp = extract_species_from_protein_text(protein_seqs[i]) if i < len(protein_seqs) else None
                clip_text_inputs.append(f"a photo of {sp.replace('_', ' ')}" if sp else "a photo of a bird")

        clip_tokens = clip_tokenizer(
            clip_text_inputs,
            max_length=clip_tokenizer.model_max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )

        species_ids_list = []
        for seq in protein_seqs:
            sp = extract_species_from_protein_text(seq)
            species_ids_list.append(species_id_map.get(sp if sp else "unknown", 0))

        return {
            "pixel_values": pixel_values,
            "input_ids": protein_tokens["input_ids"],
            "attention_mask": protein_tokens["attention_mask"],
            "clip_input_ids": clip_tokens["input_ids"],
            "clip_attention_mask": clip_tokens["attention_mask"],
            "species_ids": torch.tensor(species_ids_list, dtype=torch.long),
        }

    def collate_fn_val(examples):
        protein_seqs = [e["protein_seq"] for e in examples]
        descriptions = [e.get("description", "") for e in examples]

        protein_tokens = protein_tokenizer(
            protein_seqs,
            max_length=protein_tokenizer.model_max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )

        clip_text_inputs = []
        for i, desc in enumerate(descriptions):
            if desc:
                clip_text_inputs.append(desc)
            else:
                sp = extract_species_from_protein_text(protein_seqs[i]) if i < len(protein_seqs) else None
                clip_text_inputs.append(f"a photo of {sp.replace('_', ' ')}" if sp else "a photo of a bird")

        clip_tokens = clip_tokenizer(
            clip_text_inputs,
            max_length=clip_tokenizer.model_max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )

        return {
            "input_ids": protein_tokens["input_ids"],
            "attention_mask": protein_tokens["attention_mask"],
            "clip_input_ids": clip_tokens["input_ids"],
            "clip_attention_mask": clip_tokens["attention_mask"],
        }

    use_pin_memory = not is_npu_available()

    train_dataloader = DataLoader(
        train_dataset, shuffle=True, batch_size=args.train_batch_size,
        num_workers=args.num_workers, collate_fn=collate_fn_train, drop_last=True,
        pin_memory=use_pin_memory, prefetch_factor=args.prefetch_factor,
        persistent_workers=(args.num_workers > 0),
    )
    val_dataloader = DataLoader(
        val_dataset, shuffle=False, batch_size=args.train_batch_size,
        num_workers=args.num_workers, collate_fn=collate_fn_val, drop_last=False,
        pin_memory=use_pin_memory, prefetch_factor=args.prefetch_factor,
        persistent_workers=(args.num_workers > 0),
    )

    optimizer = torch.optim.AdamW(
        list(trainable_params) + list(classify_head.parameters()),
        lr=args.learning_rate,
        betas=(args.adam_beta1, args.adam_beta2),
        weight_decay=args.weight_decay,
        eps=args.adam_epsilon,
    )

    extra_models = [clip_text_encoder]
    if clip_vision_model is not None:
        extra_models.extend([clip_vision_model, clip_visual_projection, clip_text_projection])

    model, classify_head, optimizer, train_dataloader, val_dataloader = accelerator.prepare(
        model, classify_head, optimizer, train_dataloader, val_dataloader,
    )

    unwrapped_model = accelerator.unwrap_model(model)
    device = accelerator.device

    for m in extra_models:
        m.to(device)
        m.eval()

    if args.max_train_steps is None:
        args.max_train_steps = args.num_train_epochs * len(train_dataloader) // args.gradient_accumulation_steps

    from diffusers.optimization import get_scheduler
    lr_scheduler = get_scheduler(
        "cosine",
        optimizer=optimizer,
        num_warmup_steps=args.lr_warmup_steps,
        num_training_steps=args.max_train_steps,
    )

    logger.info(f"Using device: {device}")
    logger.info(f"NPU available: {is_npu_available()}")
    logger.info(f"Number of processes: {accelerator.num_processes}")

    global_step = 0
    best_val_loss = float('inf')

    effective_batch_size = args.train_batch_size * accelerator.num_processes * args.gradient_accumulation_steps

    logger.info("***** Running alignment training *****")
    logger.info(f"  Num GPUs = {accelerator.num_processes}")
    logger.info(f"  Per-GPU batch size = {args.train_batch_size}")
    logger.info(f"  Gradient accumulation steps = {args.gradient_accumulation_steps}")
    logger.info(f"  Effective batch size = {effective_batch_size}")
    logger.info(f"  Num train samples = {len(train_dataset)}")
    logger.info(f"  Num valid samples = {len(val_dataset)}")
    logger.info(f"  Num epochs = {args.num_train_epochs}")
    logger.info(f"  Total optimization steps = {args.max_train_steps}")
    logger.info(f"  Description dataset: {'loaded' if description_lookup else 'not provided (using species name fallback)'}")
    logger.info(f"  Loss weights: feature={args.loss_feature_weight}, "
                f"contrastive={args.loss_contrastive_weight}, classify={args.loss_classify_weight}")

    progress_bar = tqdm(range(args.max_train_steps), desc="Steps", disable=not accelerator.is_local_main_process)

    for epoch in range(args.num_train_epochs):
        model.train()
        classify_head.train()
        epoch_loss = 0.0
        epoch_feature_loss = 0.0
        epoch_contrastive_loss = 0.0
        epoch_classify_loss = 0.0
        num_steps = 0

        for step, batch in enumerate(train_dataloader):
            input_ids = batch["input_ids"]
            attention_mask = batch["attention_mask"]
            clip_input_ids = batch["clip_input_ids"]
            clip_attention_mask = batch["clip_attention_mask"]
            species_ids = batch["species_ids"]

            with accelerator.autocast():
                protein_outputs = model(
                    input_ids, attention_mask=attention_mask, return_dict=True
                )
                protein_hidden_states = protein_outputs.last_hidden_state
                protein_pooled = protein_outputs.pooler_output.to(dtype=torch.float32)

                loss_feature = torch.tensor(0.0, device=device)
                if args.loss_feature_weight > 0:
                    with torch.no_grad():
                        clip_text_outputs = clip_text_encoder(
                            input_ids=clip_input_ids,
                            attention_mask=clip_attention_mask,
                        )
                        clip_text_hidden = clip_text_outputs.last_hidden_state.detach()
                        clip_text_pooled = clip_text_outputs.pooler_output.detach()

                    loss_feature = (
                        F.mse_loss(protein_hidden_states.to(torch.float32), clip_text_hidden) +
                        F.mse_loss(protein_pooled, clip_text_pooled)
                    )

                loss_contrastive = torch.tensor(0.0, device=device)
                if args.loss_contrastive_weight > 0 and clip_vision_model is not None:
                    images = batch['pixel_values'].to(device=device, dtype=weight_dtype)
                    with torch.no_grad():
                        vision_outputs = clip_vision_model(pixel_values=images)
                        image_embeds = clip_visual_projection(vision_outputs.pooler_output)
                        image_embeds = F.normalize(image_embeds, dim=-1).detach()

                    protein_for_contrast = F.normalize(protein_pooled, dim=-1)
                    logits = protein_for_contrast @ image_embeds.T * (100.0 / 0.07)
                    labels = torch.arange(logits.shape[0], device=device)
                    loss_contrastive = F.cross_entropy(logits, labels)

                loss_classify = torch.tensor(0.0, device=device)
                if args.loss_classify_weight > 0:
                    logits = classify_head(protein_pooled)
                    loss_classify = F.cross_entropy(logits, species_ids)

                loss = (
                    args.loss_feature_weight * loss_feature +
                    args.loss_contrastive_weight * loss_contrastive +
                    args.loss_classify_weight * loss_classify
                )

            accelerator.backward(loss)
            if accelerator.sync_gradients and args.max_grad_norm > 0:
                accelerator.clip_grad_norm_(model.parameters(), args.max_grad_norm)
            optimizer.step()
            lr_scheduler.step()
            optimizer.zero_grad()

            epoch_loss += loss.item()
            epoch_feature_loss += loss_feature.item()
            epoch_contrastive_loss += loss_contrastive.item()
            epoch_classify_loss += loss_classify.item()
            num_steps += 1

            if accelerator.sync_gradients:
                global_step += 1
                progress_bar.update(1)

                if accelerator.is_local_main_process and global_step % 50 == 0:
                    logger.info(
                        f"Step {global_step}: loss={loss.item():.4f} "
                        f"(feature={loss_feature.item():.4f}, "
                        f"contrastive={loss_contrastive.item():.4f}, "
                        f"classify={loss_classify.item():.4f})"
                    )

                if accelerator.is_local_main_process and global_step % args.checkpointing_steps == 0:
                    save_path = os.path.join(args.output_dir, f"checkpoint-{global_step}")
                    os.makedirs(save_path, exist_ok=True)
                    torch.save({
                        k: v.cpu() for k, v in unwrapped_model.state_dict().items()
                        if any(n in k for n in [
                            'compression_module', 'sos_token', 'eos_token',
                            'position_embedding'
                        ])
                    }, os.path.join(save_path, "protein_clip_adapter.pt"))
                    torch.save(accelerator.unwrap_model(classify_head).state_dict(),
                               os.path.join(save_path, "classify_head.pt"))
                    logger.info(f"Saved checkpoint to {save_path}")

            if args.max_train_steps is not None and global_step >= args.max_train_steps:
                break

        avg_loss = epoch_loss / max(num_steps, 1)
        avg_feature = epoch_feature_loss / max(num_steps, 1)
        avg_contrastive = epoch_contrastive_loss / max(num_steps, 1)
        avg_classify = epoch_classify_loss / max(num_steps, 1)
        if accelerator.is_local_main_process:
            logger.info(
                f"Epoch {epoch}: avg_loss={avg_loss:.4f} "
                f"(feature={avg_feature:.4f}, contrastive={avg_contrastive:.4f}, classify={avg_classify:.4f})"
            )

        model.eval()
        classify_head.eval()
        val_loss = 0.0
        val_steps = 0
        with torch.no_grad():
            for batch in val_dataloader:
                input_ids = batch["input_ids"]
                attention_mask = batch["attention_mask"]
                clip_input_ids = batch["clip_input_ids"]
                clip_attention_mask = batch["clip_attention_mask"]

                with accelerator.autocast():
                    protein_outputs = model(
                        input_ids, attention_mask=attention_mask, return_dict=True
                    )
                    protein_hidden_states = protein_outputs.last_hidden_state

                    clip_text_outputs = clip_text_encoder(
                        input_ids=clip_input_ids,
                        attention_mask=clip_attention_mask,
                    )
                    clip_text_hidden = clip_text_outputs.last_hidden_state

                val_loss += F.mse_loss(
                    protein_hidden_states.to(torch.float32), clip_text_hidden
                ).item()
                val_steps += 1

        avg_val_loss = val_loss / max(val_steps, 1)

        val_loss_tensor = torch.tensor(avg_val_loss, device=device)
        gathered_val_losses = accelerator.gather(val_loss_tensor)
        avg_val_loss = gathered_val_losses.mean().item()

        if accelerator.is_local_main_process:
            logger.info(f"Validation MSE loss: {avg_val_loss:.6f}")

        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            if accelerator.is_local_main_process:
                save_path = os.path.join(args.output_dir, "best_model")
                os.makedirs(save_path, exist_ok=True)
                torch.save({
                    k: v.cpu() for k, v in unwrapped_model.state_dict().items()
                    if any(n in k for n in [
                        'compression_module', 'sos_token', 'eos_token',
                        'position_embedding'
                    ])
                }, os.path.join(save_path, "protein_clip_adapter.pt"))
                torch.save(accelerator.unwrap_model(classify_head).state_dict(),
                           os.path.join(save_path, "classify_head.pt"))
                logger.info(f"New best model saved (val_loss={avg_val_loss:.6f})")

        if args.max_train_steps is not None and global_step >= args.max_train_steps:
            break

    if accelerator.is_local_main_process:
        final_path = os.path.join(args.output_dir, "final_model")
        os.makedirs(final_path, exist_ok=True)
        torch.save({
            k: v.cpu() for k, v in unwrapped_model.state_dict().items()
            if any(n in k for n in [
                'compression_module', 'sos_token', 'eos_token',
                'position_embedding'
            ])
        }, os.path.join(final_path, "protein_clip_adapter.pt"))
        torch.save(accelerator.unwrap_model(classify_head).state_dict(),
                   os.path.join(final_path, "classify_head.pt"))
        logger.info(f"Training complete. Final model saved to {final_path}")

    accelerator.end_training()


if __name__ == "__main__":
    main()
